# ----------------------------------------------------------------------------
# Centralised Secret for the Centreon stack.
# In production : replace with CyberArk Conjur injection via the annotation
#   conjur.org/inject: "true"
# on the Pod, and omit this manifest.
# ----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: centreon-secret
  namespace: centreon
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "ChangeMeRoot123!"
  CENTREON_DB_PASS:      "ChangeMeCentreon456!"
  CENTREON_ADMIN_PASS:   "ChangeMeAdmin789!"
